-- 1. Insertion des Thèmes
INSERT INTO themes (name) VALUES
('Animaux'),
('Drapeaux'),
('Informatique'),
('Géographie'),
('Histoire'),
('Sciences');


-- 2. Insertion des Questions 
INSERT INTO questions (statement,theoretical_contribution,difficulty,themes_id)
VALUES
-- Animaux
('A quoi ressemble un chien ?','Le chien est un canidé domestiqué caractérisé par quatre pattes.','facile',1),
('A quoi ressemble un chat?','Le chat est un petit félin connu pour ses moustaches.','facile',1),
('A quoi ressemble un ours ?','C''est un animal robuste et imposant, couvert d''une fourrure épaisse, qui se déplace en posant toute la plante de ses pattes au sol.','facile',1),
('A quoi ressemble un lapin ?','C''est un petit animal rapide, célèbre pour ses très longues oreilles qui captent le moindre bruit et ses pattes arrière musclées pour bondir.','facile',1),
('A quoi ressemble un poisson?','C''est un animal qui vit dans l''eau, utilisant ses nageoires pour se diriger et ses branchies pour respirer sans jamais avoir besoin d''air.','facile',1),
('Lequelle de ces animaux vol?','','moyen',1),
('Lequelle de ces animaux est un félin ?','','moyen',1),
('Lequelle de ces animaux pond des oeufs?','','moyen',1),
('Lequelle de ces animaux est nocturne ?','','moyen',1),
('Lequelle est un tigre?','','moyen',1), -- Silhouette
('Quel animal vertébré possède la plus grande longévité connue ?','','difficile',1),
('Quel animal possède trois cœurs, le sang bleu et un cerveau en forme de donut ? ','','difficile',1),
('Quel est l''animal le plus venimeux au monde pour l''être humain ? ','','difficile',1),
('Quel petit mammifère est le seul à être eusocial (vivant en colonie avec une reine, comme les abeilles) ?','','difficile',1),
('Quel oiseau est capable de dormir tout en volant lors de ses migrations transocéaniques ? ','','difficile',1),

INSERT INTO questions (statement,theoretical_contribution,difficulty,themes_id)
VALUES
-- Drapeaux
('Quel est le drapeau de l''Espagne ?','','facile',2),
('Quel pays possède un drapeau avec une feuille d''érable rouge ?', 'La feuille d''érable est le symbole national du Canada depuis le 18ème siècle.', 'facile', 2),
('Quel pays a un drapeau composé d''un cercle rouge sur fond blanc ?', 'Le disque rouge représente le soleil levant.', 'facile', 2),
('Quel pays a ce drapeau : Bleu, Blanc, Rouge ?', 'Le drapeau tricolore est né durant la Révolution française.', 'facile', 2),
('Quel pays a une croix blanche sur son drapeau ?','','facile', 2),
('Quel est le drapeau du Mozambique ?','','moyen', 2),
('Quel est le drapeau du Malawi ?','', 'moyen', 2),
('Quel est le drapeau du Sénégal ?','','moyen', 2),
('Quel est le drapeau du Tchad ? ','', 'moyen', 2),
('Quel est le drapeau de l''Indonésie ?','','moyen', 2),
('Quel est le drapeau de Nauru ?','','difficile',2),
('Quel est le drapeau de l''Eswatini ?','','difficile',2),
('Quel est le drapeau du Sri Lanka ?','','difficile',2),
('Quel est le drapeau de Kiribati?','','difficile',2),
('Quel est le drapeau des Fidji ?','','difficile',2);

INSERT INTO questions (statement,theoretical_contribution,difficulty,themes_id)
VALUES
-- Informatique
('Quel est le périphérique qui permet d''écrire ?','','facile',3),
('Qu''est ce que c''est qu''un écran ?','','facile',3),
('Quel périphérique est une souris ?','','facile',3), --Penser a mettre un animal souris
('Quel est le logo Windows ?','','facile',3),
('Quel est le logo de Teams ?','','facile',3),
('Quel type de disque dur n''utilise aucune pièce mécanique et stocke les données sur de la mémoire flash ?','','moyen',3),
('Quel composant est souvent appelé le "cerveau" de l''ordinateur, car il exécute les instructions des programmes ?','','moyen',3),
('Quel est le logo actuel du navigateur de Windows ?','','moyen',3),
('Quel est le logo de Python ?','','moyen',3),
('Quel est le  logo d''HTML ?','','moyen',3),
('Qui est considérée comme la toute première personne à avoir écrit un programme informatique au 19ème siècle ?','','difficile',3),
('Lequelle de ces composants est un router ?','','difficile',3),
('Lequelle de ces cables est de l''USB C ?','','difficile',3),
('Lequelle de ces consoles est la plus vieille ? ','','difficile',3),
('Quel code est écrit en C# ? ','','difficile',3);


-- 3 Insertion des réponses
INSERT INTO answers (response_text,image_path,is_correct,questions_id)
VALUES
-- Animal
('Tortue','animals/tortue.jpg',0,1),
('Chien','animals/chien.jpg',1,1),
('Chat','animals/chat.jpg',0,1),
('Pigeon','animals/pigeon.jpg',0,1),
('Chat','animals/chat.jpg',1,2),
('Cheval','animals/cheval.jpg',0,2),
('Souris','animals/souris.jpg',0,2),
('Lapin','animals/lapin.jpg',0,2),
('Rat','animals/rat.jpg',0,3),
('Aigle','animals/aigle.jpg',0,3),
('Renard','animals/renard.jpg',0,3),
('Ours','animals/ours.jpg',1,3),
('Poisson','animals/poisson.jpg',0,4),
('Corbeau','animals/corbeau.jpg',0,4),
('Lapin','animals/lapin.jpg',1,4),
('Cheval','animals/cheval.jpg',0,4),
('Dauphin','animals/dauphin.jpg',0,5),
('Poisson','animals/poisson.jpg',1,5),
('Chien','animals/chien.jpg',0,5),
('Requin','animals/requin.jpg',0,5),
('Aigle','animals/aigle.jpg',1,6),
('Ecureuil volant','animals/ecureuilvolant.jpg',0,6),
('Grenouille','animals/grenouille.jpg',0,6),
('Poisson volants','animals/poissonvolant.jpg',0,6),
('Loup','animals/loup.jpg',0,7),
('Lion','animals/lion.jpg',1,7),
('Ours','animals/ours.jpg',0,7),
('Hyène','animals/hyène.jpg',0,7),
('Chien','animals/chien.jpg',0,8),
('Ornithorynque','animals/ornithorynque.jpg',1,8),
('Lapin','animals/lapin.jpg',0,8),
('Chat','animals/chat.jpg',0,8),
('Aigle','animals/aigle.jpg',0,9),
('Chouette','animals/chouette.jpg',1,9),
('Canard','animals/canard.jpg',0,9),
('Moineau','animals/moineau.jpg',0,9),
('Léopard','animals/léopard_silh.jpg',0,10),
('Tigre','animals/tigre_silh.jpg',1,10),
('Lion','animals/lion_silh.jpg',0,10),
('Panthère','animals/panthere_silh.jpg',0,10),
('Tortue géante','animals/tortue.jpg',0,11),
('Requin du Groenland','animals/requin_groenland.jpg',1,11),
('Baleine bleue','animals/baleine.jpg',0,11),
('Éléphant','animals/elephant.jpg',0,11),
('Méduse','animals/meduse.jpg',0,12),
('Poulpe','animals/poulpe.jpg',1,12),
('Requin','animals/requin.jpg',0,12),
('Etoile de mer','animals/etoile_mer.jpg',0,12),
('Cobra royal','animals/cobra.jpg',0,13),
('Cubo-méduse','animals/cubomeduse.jpg',1,13),
('Scorpion','animals/scorpion.jpg',0,13),
('Araignée banane','animals/araignee.jpg',0,13),
('Suricate','animals/suricate.jpg',0,14),
('Rat-taupe nu','animals/rat_taupe.jpg',1,14),
('Castor','animals/castor.jpg',0,14),
('Musaraigne','animals/musaraigne.jpg',0,14),
('Albatros','animals/albatros.jpg',0,15),
('Frégate superbe','animals/fregate.jpg',1,15),
('Hirondelle','animals/hirondelle.jpg',0,15),
('Martinet','animals/martinet.jpg',0,15);

INSERT INTO answers (response_text, image_path, is_correct, questions_id) VALUES
-- Drapeaux
('Espagne', 'flags/espagne.jpg', 1, 16),
('Portugal', 'flags/portugal.jpg', 0, 16),
('Italie', 'flags/italie.jpg', 0, 16),
('Mexique', 'flags/mexique.jpg', 0, 16),
('Canada', 'flags/canada.jpg', 1, 17),
('Liban', 'flags/liban.jpg', 0, 17),
('Vietnam', 'flags/vietnam.jpg', 0, 17),
('Pérou', 'flags/perou.jpg', 0, 17),
('Japon', 'flags/japon.jpg', 1, 18),
('Corée du Sud', 'flags/coree_sud.jpg', 0, 18),
('Bangladesh', 'flags/bangladesh.jpg', 0, 18),
('Palestine', 'flags/palestine.jpg', 0, 18),
('France', 'flags/france.jpg', 1, 19),
('Pays-Bas', 'flags/pays_bas.jpg', 0, 19),
('Russie', 'flags/russie.jpg', 0, 19),
('Luxembourg', 'flags/luxembourg.jpg', 0, 19),
('Suisse', 'flags/suisse.jpg', 1, 20),
('Danemark', 'flags/danemark.jpg', 0, 20),
('Croatie', 'flags/croatie.jpg', 0, 20),
('Grèce', 'flags/grece.jpg', 0, 20),
('Mozambique', 'flags/mozambique.jpg', 1, 21),
('Angola', 'flags/angola.jpg', 0, 21),
('Zimbabwe', 'flags/zimbabwe.jpg', 0, 21),
('Kenya', 'flags/kenya.jpg', 0, 21),
('Malawi', 'flags/malawi.jpg', 1, 22),
('Gambie', 'flags/gambie.jpg', 0, 22),
('Ouganda', 'flags/ouganda.jpg', 0, 22),
('Libéria', 'flags/liberia.jpg', 0, 22),
('Sénégal', 'flags/senegal.jpg', 1, 23),
('Mali', 'flags/mali.jpg', 0, 23),
('Cameroun', 'flags/cameroun.jpg', 0, 23),
('Guinée', 'flags/guinee.jpg', 0, 23),
('Tchad', 'flags/tchad.jpg', 1, 24),
('Roumanie', 'flags/roumanie.jpg', 0, 24),
('Andorre', 'flags/andorre.jpg', 0, 24),
('Moldavie', 'flags/moldavie.jpg', 0, 24),
('Indonésie', 'flags/indonesie.jpg', 1, 25),
('Monaco', 'flags/monaco.jpg', 0, 25),
('Pologne', 'flags/pologne.jpg', 0, 25),
('Singapour', 'flags/singapour.jpg', 0, 25),
('Nauru', 'flags/nauru.jpg', 1, 26),
('Palaos', 'flags/palaos.jpg', 0, 26),
('Tuvalu', 'flags/tuvalu.jpg', 0, 26),
('Micronésie', 'flags/micronesie.jpg', 0, 26),
('Eswatini', 'flags/eswatini.jpg', 1, 27),
('Lesotho', 'flags/lesotho.jpg', 0, 27),
('Afrique du Sud', 'flags/afrique_sud.jpg', 0, 27),
('Éthiopie', 'flags/ethiopie.jpg', 0, 27),
('Sri Lanka', 'flags/sri_lanka.jpg', 1, 28),
('Bhoutan', 'flags/bhoutan.jpg', 0, 28),
('Thaïlande', 'flags/thailande.jpg', 0, 28),
('Cambodge', 'flags/cambodge.jpg', 0, 28),
('Kiribati', 'flags/kiribati.jpg', 1, 29),
('Seychelles', 'flags/seychelles.jpg', 0, 29),
('Maldives', 'flags/maldives.jpg', 0, 29),
('Bahamas', 'flags/bahamas.jpg', 0, 29),
('Fidji', 'flags/fidji.jpg', 1, 30),
('Nouvelle-Zélande', 'flags/nouvelle_zelande.jpg', 0, 30),
('Australie', 'flags/australie.jpg', 0, 30),
('Hawaï', 'flags/hawai.jpg', 0, 30);

INSERT INTO answers (response_text, image_path, is_correct, questions_id) VALUES 
-- Informatique

('Clavier', 'it/clavier.jpg', 1, 31),
('Souris', 'it/souris_pc.jpg', 0, 31),
('Écran', 'it/ecran.jpg', 0, 31),
('Imprimante', 'it/imprimante.jpg', 0, 31),
('Écran', 'it/ecran.jpg', 1, 32),
('Imprimante', 'it/imprimante.jpg', 0, 32),
('Souris', 'it/souris_pc.jpg', 0, 32),
('Téléphone', 'it/telephone.jpg', 0, 32),
('Souris', 'it/souris_pc.jpg', 1, 33),
('Stylet', 'it/stylet.jpg', 0, 33),
('Téléphone', 'it/telephone.jpg', 0, 33),
('Tapis de Souris', 'it/tapis_souris.jpg', 0, 33),
('Windows', 'it/logo_windows.png', 1, 34),
('Apple', 'it/logo_apple.png', 0, 34),
('Linux', 'it/logo_linux.png', 0, 34),
('Android', 'it/logo_android.png', 0, 34),
('Microsoft Teams', 'it/logo_teams.png', 1, 35),
('Discord', 'it/logo_discord.png', 0, 35),
('Slack', 'it/logo_slack.png', 0, 35),
('Zoom', 'it/logo_zoom.png', 0, 35),
('SSD', 'it/ssd.jpg', 1, 36),
('HDD', 'it/hdd.jpg', 0, 36),
('CD-ROM', 'it/cd.jpg', 0, 36),
('Disquette', 'it/disquette.jpg', 0, 36),
('Processeur (CPU)', 'it/cpu.jpg', 1, 37),
('Mémoire RAM', 'it/ram.jpg', 0, 37),
('Carte Graphique', 'it/gpu.jpg', 0, 37),
('Alimentation', 'it/alimentation.jpg', 0, 37),
('Microsoft Edge', 'it/logo_edge.png', 1, 38),
('Internet Explorer', 'it/logo_ie.png', 0, 38),
('Chrome', 'it/logo_chrome.png', 0, 38),
('Firefox', 'it/logo_firefox.png', 0, 38),
('Python', 'it/logo_python.png', 1, 39),
('Java', 'it/logo_java.png', 0, 39),
('C++', 'it/logo_cpp.png', 0, 39),
('PHP', 'it/logo_php.png', 0, 39),
('HTML5', 'it/logo_html.png', 1, 40),
('CSS3', 'it/logo_css.png', 0, 40),
('JS', 'it/logo_js.png', 0, 40),
('Swift', 'it/logo_swift.png', 0, 40),
('Ada Lovelace', 'it/ada_lovelace.jpg', 1, 41),
('Grace Hopper', 'it/grace_hopper.jpg', 0, 41),
('Margaret Hamilton', 'it/margaret_hamilton.jpg', 0, 41),
('Marie Curie', 'it/marie_curie.jpg', 0, 41),
('Routeur Wi-Fi', 'it/router.jpg', 1, 42),
('Switch réseau', 'it/switch.jpg', 0, 42),
('Modem 56k', 'it/modem.jpg', 0, 42),
('Boîtier CPL', 'it/cpl.jpg', 0, 42),
('USB Type-C', 'it/usb_c.jpg', 1, 43),
('Micro-USB', 'it/micro_usb.jpg', 0, 43),
('Lightning', 'it/lightning.jpg', 0, 43),
('USB Type-A', 'it/usb_a.jpg', 0, 43),
('Magnavox Odyssey', 'it/magnavox.jpg', 1, 44),
('NES', 'it/nes.jpg', 0, 44),
('Atari 2600', 'it/atari.jpg', 0, 44),
('GameBoy', 'it/gameboy.jpg', 0, 44),
('C#', 'it/code_csharp.png', 1, 45),
('Python', 'it/code_python.png', 0, 45),
('C++', 'it/code_cpp.png', 0, 45),
('PHP', 'it/code_php.png', 0, 45);


